//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanitarianAid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Records1
    {
        public int SL { get; set; }
        public int D_ID { get; set; }
        public int N_id { get; set; }
        public int AppealId { get; set; }
        public string Productname { get; set; }
        public decimal Quantity { get; set; }
        public string Unit { get; set; }
    }
}
